# Contacts

Name | Involvement | Contact Info | Notes
----|----|----|----
Dr. Nyssa Silbiger| System Design<br /> Asst. Professor, CSUN | nyssa.silbiger@csun.edu<br /> 818-677-4427| 
Danielle Barnas| System Installation and Maintenance<br /> Silbiger Lab Tech, CSUN| danielle.barnas@csun.edu|
Bill Krohmer| Administrative Operations| william.krohmer@csun.edu
Louis Dang| Systems Engineer| louis@aqualogicinc.com| [www.aqualogicinc.com](http://www.aqualogicinc.com)
Neptune Systems| Apex Support Team| support@neptunesystems.com| [www.neptunesystems.com](http://www.neptunesystems.com)
Dickson Lab| Seawater CO2 CRMs| co2crms@ucsd.edu<br /> 858-534-2582| Marine Physical Lab<br /> Scripps Institution of Oceanography<br /> University of CA, San Diego<br /> 9500 Gilman Drive<br /> La Jolla, CA 92093-0244 USA
Science Shop| CSUN College of Science and Math Machine Shop| 818-677-3055| Location: EH 2014<br /> Available M-Th 0600-1630<br /> [www.csun.edu/Science-Shop](http://www.csun.edu/science-mathematics/science-shop)  
Perry Martin| Supervising Plumber<br /> PPM | perry.martin@csun.edu<br /> 818-677-2222| 
Will Moran| Network Engineer<br /> CSUN IT | will.moran@csun.edu<br /> 818-677-6273| 