# System Details

[**Tank System**](#Tank_System)  
[**Filtration and Recirculation System**](#Filtration_and_Recirculation_System)  
[**System Operational Sequence**](#System_Operational_Sequence)  
[**Apex Connection Series**](#Apex_Connection_Series)  
[**EB832 Outlet Connections**](#EB832_Outlet_Connections)  


<a name="Tank_System"></a> **Tank System Component List**

- Experimental Tanks (16 gal each, 24" x 15" x 15"H max) - Per tank:  
  - 1 Submersible powerhead pump ([Hydor Nano Koralia 240 powerhead](Manuals/Hydor_Nano_Pump.pdf))  
  - 1 200 W Heater ([Hydor aquarium heater](Manuals/Hydor_Heater.pdf))  
  - 1 Light ([Halo Basic M-110](Manuals/Apex_Halo.pdf))  
  - 1 Temperature probe (Apex)  
  - 1 pH probe (Apex)  
  - 1 Solenoid valve (Apex)  
  - 3 Flow sensors (Apex, FS-25 1/4" fitting, flow rates from 3-12 gph)  
  - 2 Supply lines: "N" and "S"
  - 1 Drain line: "D"
  - 1 Gate valve  
  - 1 VDM ([Apex Variable Dimming Module](Manuals/VDM_manual.pdf), 1 unit for 4 tanks)  
  - 1 FMM ([Apex Fluid Metering Module](https://www.neptunesystems.com/getstarted/fmk/))  
  - 1 PM1 ([Apex Probe Module 1](Manuals/PM1_manual.pdf))  
  - 1 Base Unit ([Apex](Manuals/Apex_Comprehensive_Reference_Manual.pdf) processing unit, 1 unit for 4 tanks)  
  - 1 EB832 ([Apex 8-outlet EnergyBar](Manuals/EB832_Guide.pdf), 1 unit for 2 tanks)  
- 1 CO2 regulator valve ([Tunze pH Controller Set, pressure reducing valve   7077/3](Manuals/Tunze_CO2_Regulator.pdf))  
  
<a name="Filtration_and_Recirculation_System"></a> **Filtration and Recirculation [System](https://github.com/dbarnas/Mesocosm_User_Manual/blob/master/Manuals/Filtration_Skid_Build_Package.pdf) Component List**

- Sump (180 gal)  
- Chiller ([AquaLogic Multi-Temp and Titan Series](Manuals/AquaLogic_Chiller.pdf))  
- Heat Pump ([AquaLogic Multi-Temp and Titan Series](Manuals/AquaLogic_Chiller.pdf))  
- PM1 (Apex Probe Module 1)  
- PhosBan chemical filter ([PhosBan Reactor 550](Manuals/Phosban_Reactor.pdf))  
- Water pump ([PerformancePro Cascade pump](Manuals/Complete_Cascade.pdf))  
- UV Sterilizer (Comet Series 95 Watt Lamp)  
- CO2 Scrubber (4 outflow tubing ports) 
- Airstones (4 units)  
- Carbon filter cells (3 units, CF28AC,28in, ActC)  
- Mesh filter (8 units, Matala Filter Media, interchanged 4 Blue high density and 4 Black low density sheets)  

<a name="System_Operational_Sequence"></a> **System Operational Sequence**

- This is a closed loop system where water from each individual 16 gallon tank will recirculate back to a main holding reservoir.  
- Flow rate for each tank is  2-6 GPH.  
- Chiller will be plumbed inline with the filtration skid which includes mechanical/biological filtration as well as UV sterilization (chemical filtration).  
- One main pump will be used to recirculate the water flow throughout the experimental tanks and the main holding reservoir.  
- Each tank will have an immersion heater that will allow tank temperatures to be set 15 degF (8.3 degC) above the main holding tank reservoir.  
  - **Note: The tank needs to be static in order to heat up to a desired temp.  Once the temperature has been reached then it can be set to flow through mode.**  
- Small sumbersible powerhead in each tank will provide water circulation throughout the tank.  
- Each tank will have (1) supply line with (2) flow sensors, (1) solenoid valve for CO2 input, and (1) gate   valve for tidal effect, and (2) drain lines with (1) flow sensor.  Incoming and outgoing flow rates will have to be manually adjusted for the tidal effect.  
  - outgoing tide: incoming flow rate to be lower than outgoing flow rate.  
  - incoming tide: incoming flow rate to be greater than outgoing flow rate.  
  - Note: The tank will not be completely empty during low tide events to prevent the recirculating powerhead from running dry.  
- Each tank will have individual LED lighting.  
- Tanks controlled via Neptune Systems Apex Controller.  Each Apex will control (4) tanks.  
  - Controllable parameters are pH, temperature, tidal effect, and lighting.  
- Air compressor connected to a CO2 scrubber will bubble air into the holding to bring pH to ambient or near-ambient conditions in the holding reservoir.  

<a name="Apex_Connection_Series"></a> **Apex Connection Series**

- Each EnergyBar connects to the Base Unit with an AquaBus cable via the AquaBus Ports for power.  (2) EB832 units per (1) Base Unit.  
- Each Solenoid valve connects to the EnergyBar via the DC24 Accessory Port on the EB832.  (2) Solenoid valves per (1) EB832.  
- (1) PM1 connects to the EnergyBar with an AquaBus cable via the AquaBus Ports, and all PM1 connect in series with each other for power.  (1) PM1 connection per (2) EB832 units.  
- VDM connects to the last PM1 in series with an AquaBus cable via the AquaBus Ports for power.  
- Temperature probe connects to the PM1 Temp Port or the Base Unit Temp Port.  (1) Temperature probe in each PM1, and (1) Temperature probe in the Base Unit.  
- pH probe connects to the PM1 pH/ORP Port or the Base Unit pH/ORP Port.  Push the BNC female connector of the probe on to the male connector and turn 1/4 turn clockwise to lock the connector in place.  (1) pH probe in each PM1, and (1) pH probe in the Base Unit.  
- [Halo light](Manuals/HALO_Quick_Start_Guide.pdf) connects to the VDM or Base Unit via the V1/V2 or V3/V4 Port.  (2) Light connections in the VDM and (2) Light connections in the Base Unit.  
- (1) FMM connects to the EnergyBar with an AquaBus cable via the AquaBus Ports, and all FMM connect in series with each other for power.  (1) FMM connection per (2) EB832 units.  
- (3) Flow sensors connect to each FMM via (3) of the numbered ports.  

<a name="EB832_Outlet_Connections"></a> **EB832 Outlet Connections**

Note: Each horizontal row on an EB832 corresponds to one tank, yielding 4 outlets per aquarium. In order:  

1. Heater  
1. Hydor Powerhead 
1. Solenoid  
1. Halo Light  
