# Controlling pH


The pH is controlled with the addition of CO2 gas to the system. The gas is delivered to the tank by air stone and is controlled through the Apex Controls with a solenoid valve connected to the EB832.

1. Once the CO2 regulator is connected to a tank, open the main tank valve.
1. Use the pressure adjusting screw to adjust the pressure (in bar) on the pressure gauge. Turning **clockwise to open**, thus increasing pressure, while turning **counterclockwise to close**, thus reducing pressure.
1. The pressure should be set to 0.5 up to 1 bar on the gauge (~7.5psi)
1. Open the fine adjustment valve to allow gas to the tank solenoid. If the pressure on the gauge is too high this may prevent the CO2 solenoid from completely closing, which will inject excess CO2 into the system.
1. Programming the solenoid: pH-TNK-#  
  
  Control type: pH Control
  Probe name: pH
  Fallback: OFF  
  High Value: 8.2
  Low Value: 7.9
  On when: High
  
  
Refer to [Comprehensive Manual](/Manuals/Apex_Comprehensive_Reference_Manual.pdf) for set point programming.