# Inventory

**Contents**  
- [**Mesocosm Tanks**](#Mesocosm_Tanks)  
- [**Filtration**](#Filtration)  
- [**Additional Items**](#Additional_Items)
  
  
<a name="Mesocosm_Tanks"></a> **Mesocosm Tanks**

| Item | Quantity | Purchase Replacement |
| :--- | :--- | :--- |
| Experimental Aquarium | 20 | 
| Aquarium Lid | 20 | 
| Lid Holding Pegs | 80 |
| 200W Heater | 20 | [$24.99 Amazon](https://www.amazon.com/Hydor-Submersible-Glass-Aquarium-Heater/dp/B00061UQ7K) |
| Suction Cup Heater Holder | 40 |
| Halo Light | 20 | [$299.99 Amazon](https://www.amazon.com/Aquatic-Life-Halo-Basic-Fixture/dp/B00T6FGDJW) |
| Halo Light Power Cords | 20 |
| Hydor Powerhead | 20 | [$34.99 Amazon](https://www.amazon.com/Hydor-Koralia-Nano-Aquarium-Circulation/dp/B0036S70ZG/ref=sr_1_2?keywords=hydor+powerhead&qid=1572981966&s=pet-supplies&sr=1-2) |
| Apex Temperature Probe | 20 | [$29.95 Bulk Reef Supply](https://www.bulkreefsupply.com/temperature-probe-neptune-systems.html) |
| Apex pH Probe | 20 | [$74.95 Bulk Reef Supply](https://www.bulkreefsupply.com/lab-grade-double-junction-ph-probe-neptune-systems.html) |
| Apex Conductivity Probe | 5 | [124.95 Bulk Reef Supply](https://www.bulkreefsupply.com/neptune-systems-lab-grade-conductivity-probe.html) |
| Suction Cup Probe Holder | 40 |
| Apex CO2 Dosing Solenoid | 20 | [$29.95 Bulk Reef Supply](https://www.bulkreefsupply.com/sv-1-solenoid-valve-neptune-systems.html) |
| Neptune FS-25 1/4" Flow Sensor | 60 | [$19.95 Bulk Reef Supply](https://www.bulkreefsupply.com/1-4-flow-sensor-fs25-neptune-systems.html) |
| Flow Solenoid/Gate Valve | 20 | [$16.99 Electric Solenoid Valves](https://www.electricsolenoidvalves.com/1-4-120v-ac-electric-plastic-solenoid-valve/) |
| Polyethylene Tubing 1/4" OD (water input) | 40 | [$15.71 for 100' Amazon](https://www.amazon.com/Dixon-0817-Polyethylene-DI087002-Natural/dp/B00LT0T3MG/ref=sr_1_4?crid=ETZJL4UXADQY&dchild=1&keywords=polyethylene+tubing+1%2F4+od&qid=1590806141&sprefix=polyethylene+tubing%2Caps%2C211&sr=8-4#feature-bullets-btf)
| Vinyl Tubing 1/4" OD (CO2 input) | 20 | [$3.92 for 20' Home Depot](https://www.homedepot.com/p/Everbilt-1-4-in-O-D-x-1-6-in-I-D-x-20-ft-Clear-PVC-Vinyl-Tubing-701968/207144351)
| Airstone | 20 | [$5.99x10pack Amazon](https://www.amazon.com/Pawfly-Cylinder-Diffuser-Airstones-Hydroponics/dp/B075QCWGZQ/ref=sr_1_5?crid=3EXLLKKDA2NYZ&keywords=airstones+for+aquariums&qid=1572983301&sprefix=airstone%2Caps%2C197&sr=8-5) |
| Apex VDM | 5 | [$99.95 Bulk Reef Supply](https://www.bulkreefsupply.com/led-pumps-control-module-vdm-neptune-systems.html) |
| Apex FMM | 20 | [$99.95 Bulk Reef Supply](https://www.bulkreefsupply.com/fmm-fluid-monitoring-module-neptune-systems.html) |
| Apex PM1 | 15 | [$84.95 Bulk Reef Supply](https://www.bulkreefsupply.com/ph-orp-probe-module-pm1-neptune-systems.html) |
| Apex Display Module | 1 | [$99.95 Bulk Reef Supply](https://www.bulkreefsupply.com/apex-display-module-neptune-systems.html) |
| Apex Base Unit | 5 | [$399.95 Bulk Reef Supply](https://www.bulkreefsupply.com/apex-controller-base-unit-neptune-systems.html) |
| Apex EB832 | 10 | [$249.95 Bulk Reef Supply](https://www.bulkreefsupply.com/energybar-832-neptune-systems.html) |
| Tunze CO2 Regulator Valve | 1 |
| Bluelight Glasses | 6 |
  
<a name="Filtration"></a> **Filtration**

| Item | Quantity | Purchase Replacement |
| :--- | :--- | :--- |
| 107 gal Sump | 1 |
| 250 gal Secondary Sump | 1 |
| Chiller | 1 |
| Apex Temperature Probe | 20 | [$29.95 Bulk Reef Supply](https://www.bulkreefsupply.com/temperature-probe-neptune-systems.html) |
| Apex pH Probe | 20 | [$74.95 Bulk Reef Supply](https://www.bulkreefsupply.com/lab-grade-double-junction-ph-probe-neptune-systems.html) |
| Apex PM1 | 1 | [$84.95 Bulk Reef Supply](https://www.bulkreefsupply.com/ph-orp-probe-module-pm1-neptune-systems.html) |
| PhosBan Reactor 550 | 2 | [$85.14 Bulk Reef Supply](https://www.bulkreefsupply.com/phosban-reactor-550.html) |
| PhosBan CDX Carbon Dioxide Absorption Media 3L | 0 | [$44.38 Bulk Reef Supply](https://www.bulkreefsupply.com/cdx-carbon-dioxide-adsorption-media-two-little-fishies.html) |
| Cascade Water Pump | 1 | 
| UV Sterilizer | 1 | 
| UV Light (UV-BULB-095W-1) | 1 | [$110 AquaLogic](https://aqualogicinc.com/product/aqua-logic-uv-lamps/)
| Air Pump | 2 |
| Air Pump tubing to Phosban Reactor 3/8" ID | 2 | [$4.93 Home Depot](https://www.homedepot.com/p/UDP-3-8-in-I-D-x-1-2-in-O-D-x-10-ft-Clear-Vinyl-Tubing-T10006008/304185141) |
| Airflow Tubing 3/16" ID | 4 | [$2.69 Petsmart](https://www.petsmart.com/fish/filters-and-pumps/air-and-water-pumps/grreat-choice-airline-tubing-5202767.html) |
| Airstone | 10 |
| Bag Filter, 50um | 3 |
| Carbon Filter Cell | 3 |
| Matala Filter, High Density (Blue) | 4 |
| Matala Filter, Low Density (Black) | 4 |

  
<a name="Additional_Items"></a> **Additional Items**

| Item | Quantity | Purchase Replacement |
| :--- | :--- | :--- |
| Apex pH 7 Calibration Pack | 5 | [Bulk Reef Supply](https://www.bulkreefsupply.com/probe-calibration-kit-ph-7-0-ph-10-0-salinity-53000us-neptune-systems.html) |
| Apex pH 10 Calibration Pack | 5 | [Bulk Reef Supply](https://www.bulkreefsupply.com/probe-calibration-kit-ph-7-0-ph-10-0-salinity-53000us-neptune-systems.html) |
| Apex 53,000 uS Conductivity Calibration Pack | 5 | [Bulk Reef Supply](https://www.bulkreefsupply.com/probe-calibration-kit-ph-7-0-ph-10-0-salinity-53000us-neptune-systems.html) |

