# Start-up Guide

**Contents**  
- [**Basic Operation**](#Basic_Operation)  
- [**Filtration**](#Filtration)  
- [**System**](#System)  

<a name="Basic_Operation"></a> **Basic Operation**

1. Operating water level in the filtration sump should be 7" in the filter cell compartment.
1. Overflow water from the tanks will feed down to the outside sump pump, then into to the filtration skid inside the Citrus Hall Field Room.  The water will flow through mesh filters and be pumped through carbon filters, the UV sterilizer, and chiller, then back to the tanks.

<a name="Filtration"></a> **Filtration**
1. Water from the Mesocosm tanks is pumped into the sump by passing through 6 mesh filters.  These filters have an accumulated biofilm to biologically filter the water before it enters the sump.
1. Water in the sump is pulled through the three carbon filters by a pump and pushed up into the UV sterilizer, where is is then directed through the chiller chamber.

<a name="System"></a> **System**
1. Inflow from the filtration sump to the mesocosm tanks
    1. Water from the chiller can be directed either back into the sump (t valve 1 is parallel with the pvc, opening flow to the sump, and t valve 2 is perpendicular to the pvc, closing flow to the tanks) or to the mesocosm tanks (t valve 1 is angled to allow partial flow to the sump and tanks, and t valve 2 is parallel with the pvc, opening flow to the tanks).
    1. T valve 1 is used to regulate the line pressure going back to the mesocosm tanks.  The more closed, the higher the pressure in the line, and the more open, the lower the pressure.
    1. The chiller has a safety flow switch that requires a minimum flow rate for the chiller to operate, so the bypass valve can be used to regulate the chiller flow as well as the container flow.
1. Outflow from the mesocosm tanks to the filtration sump
    1. Water from the tanks drains to an outdoor sump pump, which will automatically pump water out when a certain water level is reached.  This water can be directed either back into the sump (t valve 3 is opened parallel with the pvc, allowing flow to the three dump pipes into the filtration skid), or if you intend to drain water in the event of a water change or the end of an experiment, water can be directed to a drain port (t valve 3 is closed and t valve 4 is opened parallel with the pvc).
1. Overflow from sump to secondary containment
    1. When mesocosm water level falls from a high tide to low tide sequence, more water will drain to the sump than what the sump can individually hold.  Excess water can be redirected from the sump (S1) to the secondary containment (S2) by opening t valve 5 (allows simultaneous flow of filtered, chilled water to both S2 and the mesocosm tanks), and t valve 6 (allows continuous flow exchange between S1 and S2).
1. Before filling the tanks 
    1. Make sure the drain valve located under the tank is closed.
    1. Fill each rack one at a time and make sure rack and filtration skid flows are balanced before moving on to the next rack.
    1. Make sure the complete system reaches equilibrium in standard recirculation mode before setting up the tidal cycle.
